[package]
name = "zk-battleship"
version = "0.1.0"
edition = "2026"

[dependencies]
halo2_proofs = "0.3.0"
rand = "0.8"
halo2curves = "0.8.0"
bulletproofs = "5.0.0"
curve25519-dalek = "4.1.3"
merlin = "3.0.0"
blake2 = "0.10"

